name: merge

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check for token
      run: |
        # we can't use GITHUB_ prefix
        if [[ -z "${TOKEN}" ]]; then
          echo "You must include the TOKEN as an environment variable."
          exit 1
        fi
    - name: download deps
      run: |
        apt-get update && \
          apt-get install -y curl git

        # download hub release, extract binary to /usr/local/bin
        HUB_VERSION=2.12.7
        curl -s -L -o /tmp/hub.tgz https://github.com/github/hub/releases/download/v$HUB_VERSION/hub-linux-amd64-$HUB_VERSION.tgz
        tar zxvf /tmp/hub.tgz -C /tmp
        mv /tmp/hub-linux-amd64-$HUB_VERSION/bin/hub /usr/local/bin

    - name: create and merge PRs
      run: |
        # get branches for all remotes
        git fetch --all

        # clean up merged branches
        git remote prune origin

        function open_and_merge_pull_request() {
          echo "making pull request from ${GITHUB_REF} to $1"
          # create and merge
          hub pull-request -b $1 -h ${GITHUB_REF} -m 'Automated Merge' | hub merge
        }

        # if we're on master
        if [ "${GITHUB_REF}" == "refs/heads/master" ]; then

