name: merge

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: merge
      run: |
        if [[ -z "${GITHUB_TOKEN}" ]]; then
          echo "You must include the GITHUB_TOKEN as an environment variable."
          exit 1
        fi

        # all remotes
        git fetch --all
        git remote prune origin

        apt-get update && \
          apt-get install -y curl git

        # download hub release, extract binary to /usr/local/bin
        HUB_VERSION=2.12.7
        curl -s -L -o /tmp/hub.tgz https://github.com/github/hub/releases/download/v$HUB_VERSION/hub-linux-amd64-$HUB_VERSION.tgz
        tar zxvf /tmp/hub.tgz -C /tmp
        mv /tmp/hub-linux-amd64-$HUB_VERSION/bin/hub /usr/local/bin

        #
